#!/usr/local/bin/perl

use strict;
use warnings;

my $img_dir = "img/banner";
opendir DIR, "$img_dir" or die;
my @images = grep { /\.(jpg|jpeg|gif|png)$/ && -f "$img_dir/$_" } readdir(DIR);
closedir DIR;

$/ = undef;
my $file = $images[rand(scalar(@images))];
open F, '<', "$img_dir/$file" or die;
print "Content-type: image/jpeg\n\n";
print <F>;
